### ISSUE TITLE
Лабораторна. Робота з СУБД та мова SQL в системах IIoT.

### ISSUE THREAD

**Issue by pupenasan** [pupenasan/ProgIngContrSystems#24]
- [x] 6.1
- [x] 6.2
---
**Завдання для 6.3** @romamirkevich 
[план накидав](https://github.com/pupenasan/ProgIngContrSystems/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80/labdb_3rpi.md)
- [ ] виправити [тут](https://github.com/pupenasan/ProgIngContrSystems/blob/master/%D0%94%D0%BE%D0%B2%D1%96%D0%B4%D0%BD%D0%B8%D0%BA%D0%B8/RPI_install.md)
- [ ] усі необхідні налаштування (як поставити в автозагрузку, відкрити порти і т.д) написати у довідниках
- [ ] спробувати до останнього пункту проробити  
- [ ] останній пункт

**Comment by pupenasan** [comment]
@romamirkevich тестуй [Л.Р6.1](https://pupenasan.github.io/ProgIngContrSystems/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80/labdb_1maria.html)

**Comment by romamirkevich** [comment]
@pupenasan 
1. в пункті Встановлення MySQL вказать який саме дистрибутив скачувать web чи звичайний
2. в мене порт по замовчуванню був зайнятий і я міняв бо не пускало далі установлювать
2. не зрозуміло що в кінці установки MySQL робить

**Comment by pupenasan** [comment]
> 
> 
> @pupenasan
> 
>     1. в пункті Встановлення MySQL вказать який саме дистрибутив скачувать web чи звичайний
> 
Десь написано що треба ставити MySQL?

**Comment by romamirkevich** [comment]
> > @pupenasan
> > ```
> > 1. в пункті Встановлення MySQL вказать який саме дистрибутив скачувать web чи звичайний
> > ```
> 
> Десь написано що треба ставити MySQL?

https://pupenasan.github.io/ProgIngContrSystems/%D0%94%D0%BE%D0%B2%D1%96%D0%B4%D0%BD%D0%B8%D0%BA%D0%B8/windows_install.html

**Comment by pupenasan** [comment]
@romamirkevich це довідник, там багато чого буде, але треба ставити тільки `MariaDB`

**Comment by pupenasan** [comment]
@romamirkevich перевір 2-гу частину
